name: Feature Request
description: Suggest a new feature or enhancement for Lexecon
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input on making Lexecon better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm frustrated when...
        It would be better if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like Lexecon to...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I also considered...
        Another approach could be...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        In my use case, I need to...
        This feature would allow me to...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component would this feature affect?
      options:
        - Policy Engine
        - Decision Service
        - Capability System
        - Ledger
        - API Server
        - CLI
        - Identity Management
        - Model Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my use case)
        - High (Very important)
        - Medium (Would be nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Improved performance
        - Better security
        - Enhanced usability
        - Compliance requirements
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented? (Optional)
      placeholder: |
        This could be implemented by...
        Similar features in other projects...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples or mockups of how this feature would work (Optional)
      placeholder: |
        ```python
        # Example code showing how the feature might be used
        ```

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to contribute to implementing this feature
          required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with Lexecon's goals (AI governance, safety, auditability)
          required: true
        - label: I have provided sufficient detail about the use case and benefits
          required: true